
[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"
